[project]
name = "simul"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "simpy>=4.1.1",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "networkx>=3.6.1",
    "pyqt5>=5.15.11",
]
